#!/bin/bash
RESTORE=$(echo -en '\033[0m')
RED=$(echo -en '\033[00;31m')
GREEN=$(echo -en '\033[00;32m')
YELLOW=$(echo -en '\033[00;33m')
BLUE=$(echo -en '\033[00;34m')
MAGENTA=$(echo -en '\033[00;35m')

PRECOLOUR=`kubectl $@`
if [[ $@ == *"get po"* ]]; then
  sed \
  -e "1s/\(.*\)/${BLUE}\1${RESTORE}/" \
  -e "s/Running/${GREEN}Running${RESTORE}/g" \
  -e "s/Evicted/${RED}Evicted${RESTORE}/g" \
  -e "s/Terminating/${MAGENTA}Terminating${RESTORE}/g" \
  -e "s/Unknown/${RED}Unknown${RESTORE}/g" \
  -e "s/Pending/${MAGENTA}Pending${MAGENTA}/g" \
  -e "s/ImagePullBackoff/${RED}ImagePullBackoff${RESTORE}/g" \
  -e "s/CrashLoopBackOff/${RED}CrashLoopBackOff${RESTORE}/g" \
  -e "s/ContainerCreating/${YELLOW}ContainerCreating${RESTORE}/g" \
  -e "s/Error/${RED}Error${RESTORE}/g" \
  -e "s/Completed/${MAGENTA}Completed${RESTORE}/g" \
  <<<"${PRECOLOUR}"
elif [[ $@ == *"get no"* ]]; then
  sed \
  -e "1s/\(.*\)/${BLUE}\1${RESTORE}/" \
  -e "s/ Ready/ ${GREEN}Ready${RESTORE}/g" \
  -e "s/NotReady/${RED}NotReady${RESTORE}/g" \
  -e "s/Unknown/${RED}Unknown${RESTORE}/g" \
  -e "s/Pending/${MAGENTA}Pending${RESTORE}/g" \
  <<<"${PRECOLOUR}"
elif [[ $@ == *"get hpa"* ]]; then
  while read i; do
    if [[ "${i}" = NAME* ]]; then
      echo "${BLUE}${i}${RESTORE}"
    else
      VAL1=$(echo ${i} | awk -F"[%/ ]+" '{print $4}')
      VAL2=$(echo ${i} | awk -F"[%/ ]+" '{print $5}')
      if [[ "$VAL1" = *unknown* ]]; then
        echo "${i}" | sed "s/${VAL1}\/${VAL2}\%/${YELLOW}${VAL1}\/${VAL2}\%${RESTORE}/g"
      elif [ "$VAL1" -gt "$VAL2" ]; then
        echo "${i}" | sed "s/${VAL1}\%\/${VAL2}\%/${RED}${VAL1}\%\/${VAL2}\%${RESTORE}/g"
      else
        echo "${i}" | sed "s/${VAL1}\%\/${VAL2}\%/${GREEN}${VAL1}\%\/${VAL2}\%${RESTORE}/g"
      fi
    fi
  done <<<"${PRECOLOUR}"
else
  sed \
  -e "1s/\(.*\)/${BLUE}\1${RESTORE}/" \
  <<<"${PRECOLOUR}"
fi
exit 0
